version: '3'
services:
  mongo1:
    image: mongo:5.0.9
    expose:
      - 30001
    ports:
      - 30001:30001
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./file.key:/data/file.key:ro
    command: mongod --port 30001 --replSet uhndatalake --keyFile /data/file.key
  mongo2:
    image: mongo:5.0.9
    expose:
      - 30002
    ports:
      - 30002:30002
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./file.key:/data/file.key:ro
    command: mongod --port 30002 --replSet uhndatalake --keyFile /data/file.key
  mongo3:
    image: mongo:5.0.9
    expose:
      - 30003
    ports:
      - 30003:30003
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./file.key:/data/file.key:ro
    command: mongod --port 30003 --replSet uhndatalake --keyFile /data/file.key
  mongoinit:
    image: mongo:5.0.9
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongoinit.sh:/mongoinit.sh:ro
    entrypoint: ["/mongoinit.sh"]
